from src.core.source.camera import Camera as Camera
from src.core.source.dummy_poses import DummyPosesInput as DummyPosesInput
from src.core.source.mic import Mic as Mic
from src.core.source.prompt_repeater import PromptRepeater as PromptRepeater
from src.core.source.vrchat import VRChatVideo as VRChatVideo
from src.core.source.video_player import VideoPlayer as VideoPlayer
from src.core.source.text_input import TextInput as TextInput
from src.core.source.openvr_player import OpenVRPlayer as OpenVRPlayer
from src.core.source.pulse import Pulse as Pulse
